name: Bun

on:
    push:

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Bun
              run: |
                  curl -fsSL https://bun.sh/install | bash
                  echo "${HOME}/.bun/bin" >> $GITHUB_PATH

            - name: Bun is on the PATH
              run: bun
