name: Bun

on:
    push:

jobs:
    coverage:
        runs-on: ubuntu-latest

        # services:
        #     mariadb:
        #         image: mariadb:10.4
        #         ports:
        #             - 3306:3306
        #         env:
        #             MYSQL_ROOT_PASSWORD: mysql

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Bun
              run: |
                  curl -fsSL https://bun.sh/install | bash
                  echo "${HOME}/.bun/bin" >> $GITHUB_PATH

            - name: Install Dependencies
              working-directory: typescript-bun
              run: bun install

            - name: seed db
              env:
                  DB_PASSWORD: mysql
              run: |
                  sudo systemctl start mysql
                  mysql -uroot -pmysql < database/initDatabase.sql

            - name: run tests
              working-directory: typescript-bun
              run: bun test
